### ISSUE TITLE
KelvinHelmholtz problem prevents compilation on macOS

### ISSUE THREAD

**Issue by jzuhone** [gamer-project/gamer#1]
GAMER cannot be compiled on macOS because the KelvinHelmholtz problem uses the thread-safe random number generating functions `drand48_r`, etc., but these are GNU extensions and not portable (they appear to be only on Linux).

I'm looking into what more portable alternatives there may be, but I'm not sure at the moment.

**Comment by jzuhone** [comment]
I've already determined a fix and a couple of other macOS-related fixes. 

I am using gcc--I determined that with clang there are some other compilation bugs. I suppose we should try to address those as well. 

I will have a pull request sometime soon.

**Comment by hyschive** [comment]
Excellent!

Yes, using `clang` will trigger another issue related to the usage of variable-length arrays. I regard it as an important issue but haven't found a portable solution yet.

**Comment by hyschive** [comment]
Fixed with PR #2
