### ISSUE TITLE
Derived Variables in Data_000XXX files

### ISSUE THREAD

**Issue by CliffLinTw** [gamer-project/gamer#10]
I hope that I can output any custom-made derived variables to the Data_00000x files by fixing the GAMER code.
That will be more convenient than using yt tool if the new variables are important or common.

**Comment by hyschive** [comment]
Good suggestion. We should definitely support a user-defined function for that purpose. The implementation should be quite similar to outputting particle density on cells (see the runtime option `OPT__OUTPUT_PAR_DENS`)

**Comment by hyschive** [comment]
Solved by 2f196d0183d71724489a5ff45295c84e85fc8df6

**Comment by hyschive** [comment]
Solved by 2f196d0183d71724489a5ff45295c84e85fc8df6
