### ISSUE TITLE
GPU memory optimization

### ISSUE THREAD

**Issue by ChunYen-Chen** [gamer-project/gamer#103]
When enabling the `MHD` option, sometimes GPU will send the memory error since `GPU_NSTREAM` is too large by using the default value(`-1 => 16`).

**Comment by hyschive** [comment]
Possible solution: call `CUAPI_Set_Default_GPU_Parameter` and `CUAPI_MemAllocate_*` recursively during initialization until GPU memory consumption becomes acceptable.

**Comment by hyschive** [comment]
Addressed by #178
