### ISSUE TITLE
Set particle number in a test problem

### ISSUE THREAD

**Issue by hyschive** [gamer-project/gamer#119]
Currently, the total number of particles (i.e., `PAR_NPAR`) must be specified in `Input__Parameter`, which is sometimes inconvenient. We should allow test problems to set it on-the-fly.

- [x] Allow test problems to reset `amr->Par->NPar_Active_AllRank` when calling `SetParameter()`.

**Comment by jzuhone** [comment]
@hyschive 👍🏻

**Comment by hyschive** [comment]
Solved by #132 (@jzuhone)
