### ISSUE TITLE
Miss getting `NCorePerMP` for `AMPERE` architecture.

### ISSUE THREAD

**Issue by Inhyeok-Song** [gamer-project/gamer#130]
- Getting `NCorePerMP` is missed for `AMPERE` architecture  (`DeviceProp.major = 8`) 
- FYI, `TURING` architecture's `DeviceProp.major = 7`

https://github.com/gamer-project/gamer/blob/c57da444f6ac0be977db18fe6817f3f20110bafc/src/GPU_API/CUAPI_DiagnoseDevice.cu#L51-L52

**Comment by hyschive** [comment]
Addressed by 6aa5c9ceb9814922faf2b230d460a34384c727e5.

@Inhyeok-Song Thanks for reporting this issue!
