### ISSUE TITLE
Do not normalize electron density with Grackle

### ISSUE THREAD

**Issue by hyschive** [gamer-project/gamer#14]
It seems that we should NOT normalize the electron density when using the primordial chemistry in Grackle, as reported by @wt-liao. Currently, this passive scalar is normalized by default (see [here](https://github.com/gamer-project/gamer/blob/master/src/Init/Init_Field.cpp#L57)).

I don't know exactly why in Grackle electron is scaled differently. @wt-liao, could you elaborate on it when you have time?

**Comment by wt-liao** [comment]
In grackle field, electron's mass is scaled by a factor of [proton mass]/[electron mass]. One would expect the summation of mass density over all species be higher than the density field in hydro-part.

**Comment by hyschive** [comment]
@wt-liao 
To avoid possible confusion, how about applying this rescaling before and after invoking Grackle? It ensures that the definition of electron mass density throughout other parts of GAMER is consistent with other passive scalars. Specifically,
- store the original electron mass density in the GAMER field
- still normalize electron mass density so that the sum of all passive scalars is conserved
-  rescale electron density by [proton mass]/[electron mass] before invoking Grackle ([here](https://github.com/gamer-project/gamer/blob/master/src/Grackle/Grackle_Prepare.cpp#L193))
- rescale electron density back by [electron mass]/[proton mass] after invoking Grackle ([here](https://github.com/gamer-project/gamer/blob/master/src/Grackle/Grackle_Close.cpp#L133))

**Comment by wt-liao** [comment]
Yes, that sounds like a plan! 
Not sure if grackle also has the reproducibility. If yes, it might be worth checking if grackle fields are still reproducible in gamer.

**Comment by hyschive** [comment]
Fixed by #16
