### ISSUE TITLE
[Enhancement] Introduction of SYCL backend

### ISSUE THREAD

**Issue by Soujanyajanga** [gamer-project/gamer#142]
GAMER currently supports Nvidia GPUs through CUDA.

We want to contribute a new backend through Intel's oneAPI [SYCL](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-programming-guide/top/oneapi-programming-model.html). This would enable support for Nvidia, AMD and Intel devices with a single backend.
Would you be interested in this feature support?

If so, what would be your recommendations towards supporting this new backend?

**Comment by hyschive** [comment]
@Soujanyajanga Looks very interesting! My only concern is that we currently don't have enough manpower to look into it. I'll see if I can find a proper candidate for this task.

BTW, I'll close #146 as the two are basically the same.
