### ISSUE TITLE
Porting To SYCL

### ISSUE THREAD

**Issue by ysantoshkumar** [gamer-project/gamer#146]
Are you interested in having an (SYCL)[https://www.intel.com/content/www/us/en/developer/tools/oneapi/training/dpc-essentials.html#gs.bnjiaf] port of gamer as a new backend?

With the SYCL backend, we'd like to extend the existing functionalities of the gamer, by enabling the application to leverage the multi-core accelerator devices of Nvidia, AMD, and Intel vendor platforms

**Comment by hyschive** [comment]
Close since it is duplicated with #142
