### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by hyschive** [gamer-project/gamer#232]
Support Python3 in all yt scripts.

**Comment by jzuhone** [comment]
Any chance this could be support _only_ python3 in any Python script in GAMER?

**Comment by hyschive** [comment]
@jzuhone Thanks for the suggestion. Most Python scripts in GAMER are so simple that can easily support both 2 and 3 (e.g., by just switching to `print()`). But I definitely agree that for those more sophisticated scripts, we should only support Python 3 to avoid unnecessary complications. How about that?

**Comment by hyschive** [comment]
Solved by #234
