### ISSUE TITLE
Record compilation time

### ISSUE THREAD

**Issue by hyschive** [gamer-project/gamer#236]
Currently, the `Compilation Time` recorded in `Record__Note` refers to the time when compiling the file `Auxiliary/Aux_TakeNote.cpp`. So, when generating the `gamer` executable without recompiling this particular file, the `Compilation Time` won't be updated, which can be misleading.

**Comment by JeiwHuang** [comment]
How about just forcing the recompilation of `Aux_TakeNote.cpp`?

By removing or renaming `Aux_TakeNote.o` after each time we finish the compilation, we can force `make` to compile `Aux_TakeNote.cpp` again the next time we do the compilation.

- If we `make clean && make`, then it will do the same thing as before.

- If we just `make` and do not `make clean`, it will compile the modified `.cpp` and also `Aux_TakeNote.cpp`. Then we can get the updated compilation time.

- Another situation is that even if there is no source file modified and we run `make`, it will also compile `Aux_TakeNote.cpp` again to record the compilation time.

In this way, we can always record the correct time when we do the compilation.

This method can be done like this:
https://github.com/gamer-project/gamer/compare/main...JeiwHuang:gamer:RecordCompilationTime

**Comment by hyschive** [comment]
@JeiwHuang Sounds good.
@ChunYen-Chen Can you help review and test it?

**Comment by ChunYen-Chen** [comment]
@hyschive I have tested it. It looks great and elegant!

**Comment by hyschive** [comment]
Solved by #237
