### ISSUE TITLE
A more flexible makefile

### ISSUE THREAD

**Issue by lucyundead** [gamer-project/gamer#24]
It would be good if the Makefile could be modified to be more user-friendly, and help the users to avoid conflicted compile options. For example:

1.  Combine the option 'SERIAL' and 'LOAD_BALANCE', and some other options that belong to serial or parallel mode only. 

2.  It seems the fftw2 library used in GAMER needs to be compiled with "--enable-type-prefix", otherwise the code complains for not finding 'drfftw_mpi.h' (double precision) or 'srfftw_mpi.h' (single precision). It would be good if the Makefile could raise some flags to remind the user about this issue when compiling the code. 

3.  For a comparison, athena++ use a python script to modify the Makefile and print warning messages before compilation. It might be good to adopt similar methods for GAMER.

**Comment by hyschive** [comment]
Addressed by #186
