### ISSUE TITLE
Supporting a user-defined 3D external gravitational potential/acceleration

### ISSUE THREAD

**Issue by lucyundead** [gamer-project/gamer#25]
It would be good if GAMER could support user-defined 3D potential arrays. These potential arrays could either be analytical, or loaded from external files. This probably needs the following steps:

1. A tri-linear interpolation function on GPU.

2. A user interface to transfer the potential/acceleration arrays to GPU.

**Comment by hyschive** [comment]
The `HYDRO` model currently only supports analytical acceleration instead of potential. It will be great to extend it to support both analytical potential and tabular acceleration/potential.
