### ISSUE TITLE
Support more SRHD test problems

### ISSUE THREAD

**Issue by JeiwHuang** [gamer-project/gamer#271]
This is after merging SRHD PR #185.

Here are the SRHD test problems that could be added in the future:
1. Ultra-relativistic flows (Fig. 6 & Fig. 7 in [Tseng et al. 2021](https://arxiv.org/abs/2012.11130))
2. Temperature slices through the center of blast waves (Fig. 8 in [Tseng et al. 2021](https://arxiv.org/abs/2012.11130))
3. Triaxial blast wave test (Fig. 11 & Fig. 12 in [Tseng et al. 2021](https://arxiv.org/abs/2012.11130))
4. Limb-brightened jet (Fig. 13 in [Tseng et al. 2021](https://arxiv.org/abs/2012.11130) )
5. Fermi bubble (paper to be published)

**Comment by hyschive** [comment]
Integrated into #277
