### ISSUE TITLE
Remove Makefile from git version control?

### ISSUE THREAD

**Issue by jzuhone** [gamer-project/gamer#278]
The `configure.py` script is now being used to create the `Makefile` from `Makefile_base`. This means that every time it created run git notes that the file is changed from the committed version and this sometimes prevents git operations (switching branches, etc) from occurring smoothly without reverting changes in `Makefile`. 

I suggest it is no longer necessary to keep the `Makefile` itself in version control and we can remove it as such. If others are in agreement I can file the PR.

**Comment by jzuhone** [comment]
^^ @hyschive @ChunYen-Chen

**Comment by hyschive** [comment]
@jzuhone I agree with your proposal. The only reason we still keep `Makefile` is to allow for a smooth transition when first introducing `configure.py`. 

Just to be clear. What you are suggesting is to completely remove `Makefile` from git instead of just adding that to `.gitignore`, right?

**Comment by jzuhone** [comment]
I'd remove it from version control and add it to `.gitignore`.

**Comment by hyschive** [comment]
Sounds good.

**Comment by hyschive** [comment]
Solved by #279
