### ISSUE TITLE
Support PR for wiki

### ISSUE THREAD

**Issue by hyschive** [gamer-project/gamer#294]
### Goal
- Support pull requests for [wiki](https://github.com/gamer-project/gamer/wiki)

### Reference
- [Ref1](https://github.com/orgs/community/discussions/9473)
- [Ref2](https://nimblehq.co/blog/create-github-wiki-pull-request)
- [Ref3](https://gist.github.com/larrybotha/10650410)

**Comment by ChunYen-Chen** [comment]
@hyschive This issue can be closed.
