### ISSUE TITLE
Output potential by default

### ISSUE THREAD

**Issue by hyschive** [gamer-project/gamer#298]
### Goals
- [x] Enable `OPT__OUTPUT_POT` by default
- [ ] Load potential in both `Init_ByRestart_v2.cpp` and `Init_ByRestart_HDF5.cpp` if the data exists
- [ ] Calculate potential in `Init_GAMER.cpp` during restart only if the data is not loaded from the disk

### Tests
- [ ] Bitwise reproducibility after restart

**Comment by ChunYen-Chen** [comment]
1. Modify all the default values of `OPT__OUTPUT_POT` in `Input__Parameter` under `example`.

**Comment by ChunYen-Chen** [comment]
Since the output data does not store the ghost zone of potential calculated by the gravity solver, we still need to calculate the potential when the data is loaded. We do not have a trivial solution to this issue for now.
