### ISSUE TITLE
Inconsistent CoM from restart file

### ISSUE THREAD

**Issue by ChunYen-Chen** [gamer-project/gamer#312]
The CoM position is not reproducible from the restart file since the OpenMP loop used `schedule( runtime )` instead of `schedule( static )` to reduce the weighted value.

**Comment by hyschive** [comment]
@ChunYen-Chen Good catch. Could you file a PR to fix it?

**Comment by ChunYen-Chen** [comment]
@hyschive PR #313  has been made.
