### ISSUE TITLE
AutoReduceDtCoeff drops arbitrarily when trying to print snapshots closer together

### ISSUE THREAD

**Issue by milchada** [gamer-project/gamer#32]
Hi,

I'm running a binary cluster merger with MHD. A certain configuration (pretty strong B field, beta=50) ran fine when I was outputting every 0.1Gyr. I wanted a closer look, so re-ran outputting ever 0.02Gyr. Now the run crashes between two snapshots that had earlier output fine, with the following error:

ERROR : AutoReduceDtCoeff (4.3980465e-02) < AUTO_REDUCE_DT_FACTOR_MIN (5.0000000e-02) !!
        --> AUTO_REDUCE_DT failed, and the program will be terminated ......

The AutoReduceDtFactorMin was originally 0.1, I lowered it to 0.05 after it crashed once at 0.08. Apparently this keeps happening. I'm confused because this doesn't happen at coarser Dt outputs.

Do you know what could be going on?

**Comment by hyschive** [comment]
@milchada This is indeed quite strange and I'll be happy to help look into it. Can you by any chance show me how to reproduce this issue? For that, I'll need the snapshot before the crash (or at least the initial condition), source code, and all input parameter files. It will also be very helpful if you can share all the log files of your run (i.e., `stdout`, `stderr`, and all `Record__*` files).

**Comment by milchada** [comment]
@hyschive Thank you! Please find attached the stdout, stderr and Record files. 
[Record__Conservation.txt](https://github.com/gamer-project/gamer/files/5198171/Record__Conservation.txt)
[Record__DivB.txt](https://github.com/gamer-project/gamer/files/5198172/Record__DivB.txt)
[Record__Dump.txt](https://github.com/gamer-project/gamer/files/5198173/Record__Dump.txt)
[Record__LoadBalance.txt](https://github.com/gamer-project/gamer/files/5198174/Record__LoadBalance.txt)
[Record__MemInfo.txt](https://github.com/gamer-project/gamer/files/5198175/Record__MemInfo.txt)
[Record__NCorrUnphy.txt](https://github.com/gamer-project/gamer/files/5198176/Record__NCorrUnphy.txt)
[Record__Note.txt](https://github.com/gamer-project/gamer/files/5198177/Record__Note.txt)
[Record__ParticleCount.txt](https://github.com/gamer-project/gamer/files/5198178/Record__ParticleCount.txt)
[Record__PatchCount.txt](https://github.com/gamer-project/gamer/files/5198179/Record__PatchCount.txt)
[Record__Performance.txt](https://github.com/gamer-project/gamer/files/5198180/Record__Performance.txt)
[Record__TimeStep.txt](https://github.com/gamer-project/gamer/files/5198181/Record__TimeStep.txt)
[Record__Timing.txt](https://github.com/gamer-project/gamer/files/5198182/Record__Timing.txt)

[gamer.err.txt](https://github.com/gamer-project/gamer/files/5198192/gamer.err.txt)
[gamer.out.txt](https://github.com/gamer-project/gamer/files/5198193/gamer.out.txt)

The snapshot is ~25GB, so I can't attach it. What's a good way to share?

**Comment by hyschive** [comment]
@milchada This recent PR #33 solves some instability issues. Can you first test whether that helps? Note that some default configuration has changed, which may slightly alter the simulation results. Compare `Record__Note` should reveal these differences.

**Comment by milchada** [comment]
@hyschive has the pull request been completed? can i just pull the master now?

**Comment by jzuhone** [comment]
@milchada not completed yet. I'll show you how to try it in Slack

**Comment by hyschive** [comment]
@milchada I'm curious if PR #33 solves this issue?

**Comment by hyschive** [comment]
@milchada @jzuhone Does PR #33 solve this issue?

**Comment by jzuhone** [comment]
In my experience it did, but @milchada should confirm.

**Comment by milchada** [comment]
Yes, it did! Thank you for checking, Justin.
