### ISSUE TITLE
The failure of blast wave with MHD

### ISSUE THREAD

**Issue by zengbs** [gamer-project/gamer#38]
Dear developers,

Both ROE and HLLD Riemann solvers fail to simulate blast wave with MHD when magnetic field strength along the diagonal direction is 1.0. (default number is 5.0e-2; however, this number seems too small to affect blast wave) 

Run-time and compile-time parameters are attached: [mhd.tar.gz](https://github.com/gamer-project/gamer/files/5392284/mhd.tar.gz)

The tested commit version: dd974e56ec4ad87f98574836a9d63754440fc9e3

**Comment by hyschive** [comment]
`FLU_SCHEME=MHM_RP + RSOLVER=HLLD + AUTO_REDUCE_DT=0 + MINMOD_MAX_ITER=10 + MONO_MAX_ITER=10` works.
