### ISSUE TITLE
What is the CUDA version supported? 

### ISSUE THREAD

**Issue by likueimo** [gamer-project/gamer#53]
I am curios about what is the CUDA version supported or tested ? 
I guess that cuda 7.5 and cuda 10.0 is ok ?
ref :  
https://github.com/gamer-project/gamer/blob/f780b704734ee5749a887e6225b3ce9c4a95dd54/src/Makefile#L358
https://github.com/gamer-project/gamer/blob/f780b704734ee5749a887e6225b3ce9c4a95dd54/src/Makefile#L372
Thanks !

**Comment by hyschive** [comment]
@likueimo Both versions are supported. But let us know if you encounter any problems.
